apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels: {} #Added by Kustomize
  template:
    metadata:
      labels: {} #Added by Kustomize
    spec:
      containers:
        - name: quiz-app
          image: registry.wyattlbarnes.com/quiz/quiz-app
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5173
      imagePullSecrets:
        - name: regcred
